// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { existsSync } from "fs";
import { defineConfig, env } from "prisma/config";

// Load .env first (for defaults), then .env.local (for local overrides)
// .env.local takes precedence, which is the standard Next.js behavior
if (existsSync(".env")) {
  config({ path: ".env" });
}
if (existsSync(".env.local")) {
  config({ path: ".env.local", override: true });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
